force-app/main/default/objects/AreaParticipante__c/AreaParticipante__c.object-meta.xml
<CustomObject>
    <description>Área Participante - objeto criado para operação Service Cloud Wilson Sons.</description>
    <label>Área Participante</label>
    <nameField>
        <displayFormat>AREA-{000000}</displayFormat>
        <label>Área Participante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Áreas Participantes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AreaParticipante__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vincula a Área Participante ao Caso.</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Área Participante</relationshipLabel>
    <relationshipName>AreaParticipante</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AreaParticipanteTriggerHandler.cls
/**
 * @description       : Handler do trigger do objeto AreaParticipante__c. Delega operações aos serviços correspondentes.
 * @author            : Triscal
 * @group             : Área Participante
 * @last modified on  : 06-11-2026
 * @last modified by  : Jean Duarte
 **/
public inherited sharing class AreaParticipanteTriggerHandler {
    public static void beforeInsert(List<AreaParticipante__c> newList){ AreaParticipanteSLAService.beforeSave(newList, null); }
    public static void beforeUpdate(List<AreaParticipante__c> newList, Map<Id, AreaParticipante__c> oldMap){ AreaParticipanteSLAService.beforeSave(newList, oldMap); AreaParticipanteSLAService.closeSLA(newList); }
    public static void afterInsert(List<AreaParticipante__c> newList){ Set<Id> caseIds = new Set<Id>(); for (AreaParticipante__c a : newList) if (a.Caso__c != null) caseIds.add(a.Caso__c); CaseAreaParticipanteAggregationService.refreshForCases(caseIds); }
    public static void afterUpdate(List<AreaParticipante__c> newList){ Set<Id> caseIds = new Set<Id>(); for (AreaParticipante__c a : newList) if (a.Caso__c != null) caseIds.add(a.Caso__c); CaseAreaParticipanteAggregationService.refreshForCases(caseIds); }
}